using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Photography;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using SixLabors.ImageSharp.PixelFormats;
using CameraEye = Robust.Shared.Graphics.Eye;

namespace Content.Client.Photography.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoCameraWindow : FancyWindow
{
    private const float BaseMagnification = 1.5f;
    private const float PanSpeed = 4.5f;

    [Dependency] private IEyeManager _eyeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IInputManager _inputManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IGameTiming _timing = default!;

    private readonly CameraEye _viewfinderEye = new();
    private PhotoCameraBoundUserInterfaceState? _state;
    private Vector2 _panOffset;
    private bool _moveUp;
    private bool _moveDown;
    private bool _moveLeft;
    private bool _moveRight;
    private bool _hasToken;
    private bool _capturing;

    public event Action? ShutterPressed;

    public PhotoCameraWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CameraView.ViewportSize = new Vector2i(PhotographyConstants.CaptureSize, PhotographyConstants.CaptureSize);
        CameraView.Eye = _viewfinderEye;

        CameraBody.PanelOverride = Panel(Color.FromHex("#454b55"), Color.FromHex("#191c21"), 3f);
        ViewfinderBezel.PanelOverride = Panel(Color.FromHex("#101318"), Color.FromHex("#737b85"), 4f);
        ControlDeck.PanelOverride = Panel(Color.FromHex("#30353d"), Color.FromHex("#171a1f"), 2f);
        FilmPanel.PanelOverride = Panel(Color.FromHex("#272c33"), Color.FromHex("#777f88"), 1f);

        ZoomDial.SetValueWithoutEvent(1f);
        ZoomDial.OnValueChanged += _ => UpdateOptics();
        ResetButton.OnPressed += _ => ResetOptics();
        ShutterButton.OnPressed += _ => ShutterPressed?.Invoke();
        _inputManager.UIKeyBindStateChanged += OnUiKeyBindStateChanged;

        UpdateOptics();
        UpdateStatusLight(PhotoCameraStatus.NoFilm);
    }

    public void SetState(PhotoCameraBoundUserInterfaceState state)
    {
        _state = state;
        FilmLabel.Text = Loc.GetString("photo-camera-ui-film",
            ("shots", state.ShotsRemaining),
            ("capacity", state.FilmCapacity));
        StatusLabel.Text = Loc.GetString(state.Status switch
        {
            PhotoCameraStatus.NoFilm => "photo-camera-ui-status-no-film",
            PhotoCameraStatus.FilmEmpty => "photo-camera-ui-status-empty",
            PhotoCameraStatus.Processing => "photo-camera-ui-status-processing",
            _ => "photo-camera-ui-status-ready",
        });
        _capturing = state.Status == PhotoCameraStatus.Processing;
        UpdateStatusLight(state.Status);
        UpdateShutter();
    }

    public void SetTokenAvailable(bool available)
    {
        _hasToken = available;
        UpdateShutter();
    }

    public void SetCapturing()
    {
        _capturing = true;
        StatusLabel.Text = Loc.GetString("photo-camera-ui-status-processing");
        UpdateStatusLight(PhotoCameraStatus.Processing);
        UpdateShutter();
    }

    public void ShowResult(PhotoCaptureResult result)
    {
        _capturing = false;
        StatusLabel.Text = Loc.GetString(result switch
        {
            PhotoCaptureResult.Success => "photo-camera-ui-result-success",
            PhotoCaptureResult.CameraNotHeld => "photo-camera-ui-result-not-held",
            PhotoCaptureResult.NoFilm => "photo-camera-ui-status-no-film",
            PhotoCaptureResult.FilmEmpty => "photo-camera-ui-status-empty",
            PhotoCaptureResult.Cooldown => "photo-camera-ui-result-cooldown",
            PhotoCaptureResult.Busy => "photo-camera-ui-status-processing",
            PhotoCaptureResult.QueueFull => "photo-camera-ui-result-busy",
            PhotoCaptureResult.InvalidImage => "photo-camera-ui-result-invalid-image",
            PhotoCaptureResult.StorageFull => "photo-camera-ui-result-storage-full",
            _ => "photo-camera-ui-result-invalid-session",
        });
        UpdateStatusLight(result == PhotoCaptureResult.Success
            ? PhotoCameraStatus.Ready
            : _state?.Status ?? PhotoCameraStatus.NoFilm);
        UpdateShutter();
    }

    public void Capture(CopyPixelsDelegate<Rgba32> callback)
    {
        CameraView.Screenshot(callback);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var source = _eyeManager.CurrentEye;
        _viewfinderEye.Position = source.Position;
        _viewfinderEye.Rotation = source.Rotation;
        _viewfinderEye.DrawFov = source.DrawFov;
        _viewfinderEye.DrawLight = source.DrawLight;

        UpdatePan(args.DeltaSeconds, source.Zoom, source.Rotation);
        _viewfinderEye.Offset = source.Offset + GetGridRotation().RotateVec(_panOffset);
        _viewfinderEye.Zoom = source.Zoom / (BaseMagnification * ZoomDial.Value);

        UpdateShutter();
    }

    private void UpdateShutter()
    {
        var controlsDisabled = _capturing;
        ZoomDial.Disabled = controlsDisabled;
        ResetButton.Disabled = controlsDisabled;

        ShutterButton.Disabled = !_hasToken ||
                                 controlsDisabled ||
                                 _state is not { Status: PhotoCameraStatus.Ready } state ||
                                 state.CooldownEnds > _timing.CurTime;
    }

    private void ResetOptics()
    {
        _panOffset = Vector2.Zero;
        ZoomDial.Value = 1f;
        UpdateOptics();
    }

    private void UpdateOptics()
    {
        ClampPan(_eyeManager.CurrentEye.Zoom);
        PanValue.Text = ZoomDial.Value <= 1f
            ? Loc.GetString("photo-camera-ui-pan-locked")
            : Loc.GetString("photo-camera-ui-pan-value",
                ("x", _panOffset.X.ToString("+0.00;-0.00;0.00")),
                ("y", _panOffset.Y.ToString("+0.00;-0.00;0.00")));
        ZoomValue.Text = Loc.GetString("photo-camera-ui-zoom-value", ("value", ZoomDial.Value.ToString("0.##")));
    }

    private void UpdatePan(float frameTime, Vector2 sourceZoom, Angle viewRotation)
    {
        var direction = new Vector2(
            (_moveRight ? 1f : 0f) - (_moveLeft ? 1f : 0f),
            (_moveUp ? 1f : 0f) - (_moveDown ? 1f : 0f));

        var previous = _panOffset;
        if (!_capturing && direction != Vector2.Zero)
        {
            // WASD describes movement on the screen. Convert it into the grid's local axes so
            // rotating the view automatically swaps/inverts the X and Y controls as appropriate.
            // Eye rotation is applied with the opposite sign by the view matrix. Convert the
            // screen direction into world space first, then from world into grid-local space.
            var screenToGridRotation = -viewRotation - GetGridRotation();
            var gridDirection = RotateToGridCardinal(Vector2.Normalize(direction),
                screenToGridRotation.GetCardinalDir());
            _panOffset += gridDirection * PanSpeed * frameTime;
        }

        ClampPan(sourceZoom);
        if (previous != _panOffset)
            UpdateOptics();
    }

    private static Vector2 RotateToGridCardinal(Vector2 direction, Direction rotation)
    {
        // Avoid trigonometry here: even a tiny fractional grid rotation would otherwise make
        // one WASD key alter both displayed coordinates.
        return rotation switch
        {
            Direction.East => new Vector2(-direction.Y, direction.X),
            Direction.North => -direction,
            Direction.West => new Vector2(direction.Y, -direction.X),
            _ => direction,
        };
    }

    private void ClampPan(Vector2 sourceZoom)
    {
        var zoom = ZoomDial.Value;
        if (zoom <= 1f)
        {
            _panOffset = Vector2.Zero;
            return;
        }

        var originalHalfView = sourceZoom *
                               (PhotographyConstants.CaptureSize / (2f * EyeManager.PixelsPerMeter * BaseMagnification));
        var maxOffset = originalHalfView * (1f - 1f / zoom);

        // Keep the permitted square fixed to the grid instead of rotating it with the world/view.
        _panOffset = Vector2.Clamp(_panOffset, -maxOffset, maxOffset);
    }

    private Angle GetGridRotation()
    {
        if (!_entityManager.TryGetComponent<TransformComponent>(_playerManager.LocalEntity, out var playerXform))
            return Angle.Zero;

        var transform = _entityManager.System<SharedTransformSystem>();
        if (_entityManager.TryGetComponent<TransformComponent>(playerXform.GridUid, out var gridXform))
            return transform.GetWorldRotation(gridXform);

        // On a map entity there is no grid, so use the map's own coordinate axes.
        return transform.GetWorldRotation(playerXform) - playerXform.LocalRotation;
    }

    private bool OnUiKeyBindStateChanged(BoundKeyEventArgs args)
    {
        if (!IsOpen)
            return false;

        var pressed = args.State == BoundKeyState.Down;
        if (args.Function == EngineKeyFunctions.MoveUp)
            _moveUp = pressed;
        else if (args.Function == EngineKeyFunctions.MoveDown)
            _moveDown = pressed;
        else if (args.Function == EngineKeyFunctions.MoveLeft)
            _moveLeft = pressed;
        else if (args.Function == EngineKeyFunctions.MoveRight)
            _moveRight = pressed;
        else
            return false;

        return true;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        if (_capturing || args.Delta.Y == 0f)
            return;

        ZoomDial.Value += MathF.Sign(args.Delta.Y) * ZoomDial.Step;
        args.Handle();
    }

    private void UpdateStatusLight(PhotoCameraStatus status)
    {
        var color = status switch
        {
            PhotoCameraStatus.Ready => Color.FromHex("#69d17d"),
            PhotoCameraStatus.Processing => Color.FromHex("#f0c568"),
            _ => Color.FromHex("#d96464"),
        };

        StatusLed.PanelOverride = Panel(color, Color.FromHex("#121519"), 2f);
    }

    private static StyleBoxFlat Panel(Color background, Color border, float thickness)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(thickness),
        };
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _inputManager.UIKeyBindStateChanged -= OnUiKeyBindStateChanged;

        base.Dispose(disposing);
    }
}
