using Content.Client.UserInterface.Controls;
using Content.Shared.Photography;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Photography.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoWindow : FancyWindow
{
    public PhotoWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void ShowLoading()
    {
        Image.Visible = false;
        Status.Visible = true;
        Status.PlaceholderText = Loc.GetString("photograph-ui-loading");
    }

    public void ShowImage(Texture texture)
    {
        Image.Texture = texture;
        Image.Visible = true;
        Status.Visible = false;
    }

    public void ShowError(string message)
    {
        Image.Texture = null;
        Image.Visible = false;
        Status.Visible = true;
        Status.PlaceholderText = message;
    }
}
